version : 1
#???????O??L??????
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s (%(name)s) [%(levelname)s] %(message)s"

handlers:
  # conosle?o??
  console:  
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  # ????????X?V?t?@?C??
  rotate_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: reflection.log
    when: midnight
    backupCount: 365
    encoding: utf-8
  
loggers:
  uvicorn.error:
    propagate: true
    
  uvicorn.access:
    level: INFO
    propagate: true
    handlers:
    - console
    - rotate_file
  
  API:
    level: INFO
    handlers:
      - console
      - rotate_file